[package]
name = "seal-tools"
version = "2.1.2"
edition = "2021"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
clap = { version = "4.3.16", features = ["derive"] }
inquire = "0.6.2"
zip = "0.6.6"
tar = "0.4.39"
flate2 = "1.0.26"